DESD/DESD/urls.py
"""
URL configuration for DESD project.

The urlpatterns list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    
Add an import:  from my_app import views
Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    
Add an import:  from other_app.views import Home
Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    
Import the include() function: from django.urls import include, path
Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import path, include
from . import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('check_session_data/', views.check_session_data, name='check_session_data'),
    path('', include('login_page.urls'), name='login_page'),
    path('', include('sign_up.urls'), name='signup'),
    path('account_settings/', include('account_settings.urls')),
    path('admin_payments/', include('admin_payments.urls')),
    path('admin_reports/', include('admin_reports.urls')),
    path('admin_staffrates/', include('admin_staffrates.urls')),
    path('admin_appointments/', include('admin_appointments.urls', namespace='appointment_appointments')),
    path('booking/', include("patients_appointments.urls", namespace='booking')),
    path('patient_main/', include("patients_dashboard.urls")),
    path('patient_prescription/', include("patients_prescription.urls"), name='patients_prescription'),
    path('doctor_nurse_main/', include("doctor_nurse_dashboard.urls"), name='doctor_nurse_main'),
    path('doctor_nurse_prescriptions/', include("doctor_nurse_prescriptions.urls"), name='doctor_nurse_prescriptions'),
    path('doctor_nurse_appointments/', include("doctor_nurse_appointments.urls", namespace='doctor_nurse_appointments')),
    path('admin_main/', include("admins_dashboard.urls"), name='admin_main'),
    path('', include('staff_signup.urls'), name='staff_signup'),
    path('', include('patient_signup.urls'), name='patient_signup'),
]

DESD/patients_appointments/urls.py
from django.urls import path
from . import views

app_name = 'patients_appointments'

urlpatterns = [
    path('', views.new_booking, name="booking"),
    path('fetch_calendar', views.fetch_calendar, name='fetch_calendar'),
    path('slot_selection_handling/', views.slot_selection_handling, name="slot_selection_handling"),
    path('patient_slot_confirmation/', views.patient_slot_confirmation, name="patient_slot_confirmation"),
    path('slot_confirmation_handling/', views.slot_confirmation_handling, name='slot_confirmation_handling'),
    path('patient_appointment_confirm/', views.patient_appointment_confirm, name='patient_appointment_confirm'),
    path('patient_appointment_fail/', views.patient_appointment_fail, name='patient_appointment_fail'),
    path('patient_appointments_list/', views.patient_appointments_list, name='patient_appointments_list'),
    path('patient_appointments_invoice/', views.patient_appointments_invoice, name="patient_appointments_invoice"),
    path('clear_amend_item/', views.clear_amend_item, name="clear_amend_item"),
    path('cancel_appointment', views.cancel_appointment, name='cancel_appointment'),
    path('patient_appointments_reason', views.patient_appointments_reason, name='patient_appointments_reason'),
]

DESD/patients_dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.patients_dashboard_view, name='patient_main'),
]

DESD/patients_dashboard/views.py
from django.shortcuts import render, redirect
from database_models.models import PrescriptionsAssignments
from DESD.views import verify_user_role

"""
Checks if the patient has any prescriptions with collection_status = 'waiting to collect'.
Returns True if at least one prescription is found, otherwise returns False.
"""
def check_not_collected_prescriptions(patient_id):
    return PrescriptionsAssignments.objects.filter(appointment__patient_id=patient_id, collection_status='waiting to collect').exists()

"""
Renders the main page for patients, passes the user data and the presecription notification as context.
"""
def patients_dashboard_view(request):
    user_data = request.session.get('user_data')
    if not verify_user_role(user_data.get('role'), 'patient'):
        return redirect('/')

    prescription_notification = check_not_collected_prescriptions(user_data.get('patient_id'))

    context = {
        'user_data': user_data,
        'new_prescriptions_status': prescription_notification,
    }
    return render(request, 'patients_dashboard.html', context)

DESD/patients_dashboard/templates/patients_dashboard.html
{% extends "base_and_header.html" %}
{% load static %}
{% block content %}
  <style>
      .dashboard-main {
          height: 80vh;
          display: flex;
          justify-content: center;
          align-items: center;
          flex-direction: column;
          /* Center content vertically */
      }

      .dashboard-header {
          margin-bottom: 2rem;
          text-align: center;
      }

      .btn-container {
          display: flex;
          flex-wrap: wrap;
          /* Allow buttons to wrap to the next line if needed */
          justify-content: center;
          gap: 1rem;
          /* Add space between buttons */
          max-width: 550px;
          /* Limit width of button container */
          width: 100%;
          /* Ensure container takes full width */
      }

      .btn-max-width {
          width: 100%;
          /* Ensure buttons take full width of container */
      }

      @keyframes pulse {
          0% {
              transform: scale(1);
          }

          50% {
              transform: scale(1.2);
              /* Expand */
          }

          100% {
              transform: scale(1);
          }
      }

      .pulse-animation {
          animation: pulse 1.5s infinite;
          /* Adjust animation duration as needed */
      }

      .pulse-animation.translate-middle {
          transform: translate(-50%, -50%) !important;
      }
  </style>
  <div class="container dashboard-main col-12">
    <div class="dashboard-header">
      <h2>Hi, {{ user_data.name }}.</h2>
      {% if new_prescriptions_status %}<h2>Your prescriptions are ready to collect!</h2>{% endif %}
    </div>
    <div class="btn-container">
      <button class="btn btn-main btn-lg btn-max-width"
              type="button"
              onclick="navigateToUrl('{% url 'patients_appointments:booking' %}')">
        <i class="bi bi-clipboard2-heart"></i>
        Book an Appointment
      </button>
      <button class="btn btn-main btn-lg btn-max-width"
              type="button"
              onclick="navigateToUrl('{% url 'patients_appointments:patient_appointments_list' %}')">
        <i class="bi bi-person-lines-fill"></i>
        View Appointments
      </button>
      <button class="btn btn-main btn-lg btn-max-width"
              type="button"
              onclick="navigateToUrl('{% url 'patients_prescription' %}')"
              style="position: relative">
        <i class="bi bi-capsule"></i>
        View Prescriptions
        {% if new_prescriptions_status %}
          <span class="position-absolute p-2 bg-danger border border-light rounded-circle pulse-animation pulse-animation">
            <span class="visually-hidden">New prescriptions</span>
          </span>
        {% endif %}
      </button>
      <button class="btn btn-main btn-lg btn-max-width"
              type="button"
              onclick="navigateToUrl('{% url 'index' %}')">
        <i class="bi bi-gear-fill"></i>
        Account Settings
      </button>
      <button class="btn btn-main btn-lg btn-max-width"
              type="button"
              onclick="navigateToUrl('{% url 'login_page' %}')">
        <i class="bi bi-box-arrow-left"></i>
        Logout
      </button>
      {% comment %} <form id="logoutForm" method="post" action="{% url 'login_page' %}">
        {% csrf_token %}
        <input type="hidden" name="logout" value="1" />
        <button class="btn btn-main btn-lg btn-max-width" type="button" onclick="logout()">Logout</button>
      </form> {% endcomment %}
    </div>
  </div>
  {% comment %} <script>
    function FlushSession(prescriptin_assignment_id) {
      request.session.flush();
  } {% endcomment %}
{{ redirect_to_login_immediately }}
  {% endblock %}