DESD/DESD/urls.py
"""
URL configuration for DESD project.

The urlpatterns list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    
Add an import:  from my_app import views
Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    
Add an import:  from other_app.views import Home
Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    
Import the include() function: from django.urls import include, path
Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import path, include
from . import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('check_session_data/', views.check_session_data, name='check_session_data'),
    path('', include('login_page.urls'), name='login_page'),
    path('', include('sign_up.urls'), name='signup'),
    path('account_settings/', include('account_settings.urls')),
    path('admin_payments/', include('admin_payments.urls')),
    path('admin_reports/', include('admin_reports.urls')),
    path('admin_staffrates/', include('admin_staffrates.urls')),
    path('admin_appointments/', include('admin_appointments.urls', namespace='appointment_appointments')),
    path('booking/', include("patients_appointments.urls", namespace='booking')),
    path('patient_main/', include("patients_dashboard.urls")),
    path('patient_prescription/', include("patients_prescription.urls"), name='patients_prescription'),
    path('doctor_nurse_main/', include("doctor_nurse_dashboard.urls"), name='doctor_nurse_main'),
    path('doctor_nurse_prescriptions/', include("doctor_nurse_prescriptions.urls"), name='doctor_nurse_prescriptions'),
    path('doctor_nurse_appointments/', include("doctor_nurse_appointments.urls", namespace='doctor_nurse_appointments')),
    path('admin_main/', include("admins_dashboard.urls"), name='admin_main'),
    path('', include('staff_signup.urls'), name='staff_signup'),
    path('', include('patient_signup.urls'), name='patient_signup'),
]

DESD/doctor_nurse_appointments/urls.py
from django.urls import path
from . import views

app_name = 'doctor_nurse_appointments'

urlpatterns = [
    path('', views.appointments_list, name="appointments_list"),
    path('amend_booking_handling/', views.amend_booking_handling, name="amend_booking_handling"),
    path('amend_booking/', views.amend_booking, name="amend_booking"),
    path('cancel_appointment', views.cancel_appointment, name='cancel_appointment'),
    path('amend_confirmation_handling/', views.amend_confirmation_handling, name='amend_confirmation_handling'),
    path('cancel_reason/', views.cancel_reason, name='cancel_reason'),
    path('forward_detail/', views.forward_detail, name='forward_detail'),
    path('forward_appointment/', views.forward_appointment, name='forward_appointment'),
    path('prescribe_appointment/', views.prescribe_appointment, name='prescribe_appointment'),
    # path('clear_amend_item/', views.clear_amend_item, name="clear_amend_item"),
]

DESD/doctor_nurse_appointments/models.py
from django.db import models

# Create your models here.

DESD/doctor_nurse_appointments/views.py
from datetime import datetime, timedelta
from django.http import JsonResponse
from django.forms.models import model_to_dict
from django.core.serializers.json import DjangoJSONEncoder
from django.core.serializers import serialize
import json
from django.shortcuts import redirect, render
from django.urls import reverse
from database_models.models import *
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist
from fuzzywuzzy import fuzz

def update_list(request): #backend calculation code 
    if request.method == 'GET':
        outcome = request.GET.get('outcome')
        if not request.session.get('user_data'):
            return redirect('doctor_nurse_main')
        user_data = request.session.get('user_data')
        staff_id = user_data.get('staff_id')
        cancel_types = CancellationTypes.objects.all()[:3]
        cancel_type_list = [{'id': ct.cancellation_type_id, 'type': ct.cancellation_type} for ct in cancel_types]

        appointments_data = Appointments.objects.filter(staff_id=staff_id,
                                                        appointment_outcome=outcome
                                                ).select_related('patient__user' 
                                                ).values(
                                                    'appointment_id',
                                                    'appointment_date',
                                                    'appointment_start',
                                                    'appointment_end',
                                                    'appointment_status',
                                                    'appointment_outcome',
                                                    'patient_id',
                                                    'patient__user__name',
                                                ).order_by('appointment_date', 'appointment_start')
        
        context = {
            'appointment': list(appointments_data),
            'cancel_type': cancel_type_list,
        }
    
    return JsonResponse(context, safe=False)


def appointments_list(request):
    if not request.session.get('user_data'):
        return redirect('doctor_nurse_main')
    
    if request.method == 'GET' and 'outcome' in request.GET:
        return update_list(request)

    user_data = request.session.get('user_data')
    staff_id = user_data.get('staff_id')
    
    appointments = Appointments.objects.filter(staff_id=staff_id,
                                               appointment_status='upcoming',
                                            ).select_related('patient__user'
                                            ).values(
                                                'appointment_id',
                                                'appointment_date',
                                                'appointment_start',
                                                'appointment_end',
                                                'appointment_status',
                                                'appointment_outcome',
                                                'patient_id',
                                                'patient__user__name',
                                            ).order_by('-appointment_date', '-appointment_start')

    cancel_types = CancellationTypes.objects.all()[:3]
    cancel_type_list = [{'id': ct.cancellation_type_id, 'type': ct.cancellation_type} for ct in cancel_types]
    
    context = {
        'appointments': appointments,
        'cancel_types': cancel_type_list,
        'user_data': user_data,
    }

    response = render(request,'doctor_nurse_appointments.html', context)

    return response 


def amend_booking_handling(request):
    user_data = request.session.get('user_data')
    staff_id = user_data.get('staff_id')
    role = user_data.get('role')

    if request.method == 'POST':
        selected_date = request.POST.get('date')
        selected_start = request.POST.get('start')
        selected_end = request.POST.get('end')
        selected_patient = request.POST.get('patient')
        selected_date = datetime.strptime(selected_date, "%Y-%m-%d")
    else:
        selected_date_str = request.GET.get('date')
        selected_date = datetime.strptime(selected_date_str, "%Y-%m-%d")

    selected_day = selected_date.weekday() + 1

    try:
        schedule = Schedules.objects.get(day_id=selected_day, role=role)
    except Schedules.DoesNotExist:
        return JsonResponse({'error': "No Schedule found for the selected day."}, status=404)
    
    slots = Slots.objects.filter(schedule=schedule).order_by('start_time')
    appointments = Appointments.objects.filter(
                                            staff_id=staff_id,
                                            appointment_date=selected_date
                                            )
    
    slots_info = []
    duration_minutes_mapping = {1: 10, 2: 20, 3: 30}

    for slot in slots:
        duration_in_minutes = duration_minutes_mapping.get(slot.duration.duration_length)
        slot_end_time = (datetime.combine(selected_date, slot.start_time) + timedelta(minutes=duration_in_minutes)).time()

        overlapping_appointments = appointments.filter(
            Q(appointment_start__lt=slot_end_time),
            Q(appointment_end__gt=slot.start_time)
        ).exists()

        slots_info.append({
            'start_time': slot.start_time.strftime("%H:%M"),
            'end_time': slot_end_time.strftime("%H:%M"),
            'is_available': not overlapping_appointments
        })

    if request.method == 'POST':
        prev_appointment = Appointments.objects.select_related('patient__user').get(
                                                                patient_id=selected_patient,
                                                                appointment_date=selected_date,
                                                                appointment_start=selected_start,
                                                                appointment_end=selected_end,
                                                                staff_id=staff_id
                                                            )
    
        prev_appointment_dict = {
            'appointment_id': prev_appointment.appointment_id,
            'appointment_date': prev_appointment.appointment_date,
            'appointment_start': prev_appointment.appointment_start,
            'appointment_end': prev_appointment.appointment_end,
            'staff_id': prev_appointment.staff_id,
            'patient_id': prev_appointment.patient_id,
            'patient_name': prev_appointment.patient.user.name,
        }

        request.session['amendSlot'] = {
            'slots_info': json.dumps(slots_info, cls=DjangoJSONEncoder),
            'appointment': json.dumps(prev_appointment_dict, cls=DjangoJSONEncoder),
        }
        redirect_url = reverse('doctor_nurse_appointments:amend_booking')
        return JsonResponse({'status': 'success', 'redirect_url': redirect_url})
    else: 
        return JsonResponse({'slots': slots_info})

def amend_booking(request):
    if not request.session.get('user_data'):
        return redirect('doctor_nurse_main')
    
    user_data = request.session.get('user_data')
    info = request.session.get('amendSlot')

    slots_info = json.loads(info.get('slots_info'))
    appointment = json.loads(info.get('appointment'))

    context = {
        'slots': slots_info,
        'appointment': appointment,
        'user_data': user_data,
    }

    return render(request, 'doctor_nurse_amendment.html', context)
    
def cancel_appointment(request):
    if request.method == 'POST':
        if not request.session.get('user_data'):
            return redirect('doctor_nurse_main')
        
        appointment_id = int(request.POST.get('id'))
        reason_id = int(request.POST.get('reason'))

        try:
            appointment = Appointments.objects.get(appointment_id=appointment_id)
            cancel_reason = CancellationTypes.objects.get(cancellation_type_id=reason_id)

            AppointmentCancellations.objects.update_or_create(
                appointment=appointment,
                description= cancel_reason.cancellation_type,
                cancellation_type_id=reason_id
            )

            appointment.appointment_status = 'cancelled'
            appointment.appointment_outcome = 'cancelled'
            appointment.save()
            return JsonResponse("Appointment cancelled successfully.", safe=False)
        except ObjectDoesNotExist:
            return JsonResponse("No appointment found with the given details.", safe=False)
        
def amend_confirmation_handling(request):
    if request.method == 'POST':
        if not request.session.get('user_data'):
            return redirect('doctor_nurse_main')
        appointment_id = request.POST.get('id')
        selected_date = request.POST.get('date')
        start_time = request.POST.get('start_time')
        end_time = request.POST.get('end_time')

        date = datetime.strptime(selected_date, '%Y-%m-%d').date()
        start_time = datetime.strptime(start_time, '%H:%M').time()
        end_time = datetime.strptime(end_time, '%H:%M').time()

        try:
            appointment = Appointments.objects.get(appointment_id=appointment_id)
            appointment.appointment_date = date
            appointment.appointment_start = start_time
            appointment.appointment_end = end_time
            appointment.save()

            return JsonResponse({"status": "success", "message": "Appointment updated successfully."})
        except Appointments.DoesNotExist:
            return JsonResponse({"status": "error", "message": "Appointment not found."}, status=404)
        except Exception as e:

DESD/doctor_nurse_appointments/templates/doctor_nurse_amendment.html
{% extends "base_and_header.html" %}
{% load static %}
{% block content %}
{% load custom_filters %}

    <style>
        .main-container {
            display: flex;
            flex-direction: column;
            flex-wrap: nowrap;
            align-items: center;
        }

        .booking-details-text {
            font-size: 135%;
        }

        .col {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .row {
            width: inherit;
        }

        .form-select {
            background-color: var(--verdigris);
        }

    </style>
    <head>
        <meta name="csrf-token" content="{{ csrf_token }}" />
    </head>
    <main class="form-signin d-flex justify-content-center align-items-center w-100 mt-4">
        <div>
            <div class="col-md-12 main-container">
                <h1 class="mb-4">Amend booking details.</h1>
            </div>
                <div class="row">
                    <div class="col">
                        <h2>Date</h2>
                            <div class="mb-4">
                                <input type="date" id="appointmentDate" name="appointment_date" value="{{ appointment.appointment_date }}" min="" onchange="validateDate()">
                            </div>
                    </div>
                    <div class="col">
                        <h2>Time</h2>
                        <div class="mb-4">
                        {% if slots %}
                            <select id="timeslotSelect" class="form-select form-select-lg" aria-label="Select timeslot">
                                {% for slot in slots %}
                                    <option value="{{ slot.start_time }}-{{ slot.end_time }}" {% if not slot.is_available %}disabled{% endif %}>
                                        {{ slot.start_time }} to {{ slot.end_time }}
                                    </option>
                                {% endfor %}
                            </select>
                        {% else %}
                            <h2>No available slots.</h2>
                        {% endif %}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <h2>Patient</h2>
                        <div class="mb-4 booking-details-text">{{ appointment.patient_name }}</div>
                    </div>
                </div>
                <div class="confirm-back row">
                    <div class="col">
                        <button class="btn btn-main btn-lg w-100" type="button" onclick="navigateToUrl('{% url 'doctor_nurse_appointments:appointments_list' %}')">Back</button>
                    </div>
                    <div class="col">
                        <button class="btn btn-main btn-lg w-100"
                            type="submit"
                            onclick="amendConfirmation()">Confirm</button>
                </div>    
                </div>
            </div>
        </div>
    </main>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var today = new Date();
        var dd = String(today.getDate()).padStart(2, '0');
        var mm = String(today.getMonth() + 1).padStart(2, '0');
        var yyyy = today.getFullYear();

        today = yyyy + '-' + mm + '-' + dd;
        document.getElementById('appointmentDate').setAttribute('min', today);

        var appointmentDate = '{{appointment.appointment_date}}';
        document.getElementById('appointmentDate').value = appointmentDate;
        validateDate();
    });

    function toLocalDateISOString(date) {
        var localDate = new Date(date);
        var timeZoneOffset = localDate.getTimezoneOffset() * 60000;
        var adjustedDate = new Date(localDate.getTime() - timeZoneOffset);

        return adjustedDate.toISOString().slice(0, 10);
    }

    function validateDate() {
        var input = document.getElementById('appointmentDate');
        var selectedDate = new Date(input.value);
        var day = selectedDate.getDay();

        if(day === 0 || day === 6) {
            alert('Weekends are not available for appointments. Please select another date.');
            input.value = ''; 
            return;
        }

        var formattedDate = toLocalDateISOString(selectedDate);

        $.ajax({
            url: "{% url 'doctor_nurse_appointments:amend_booking_handling' %}",
            type: "GET",
            data: {
                'date': formattedDate,
            },
            success: function(data) {
                updateSlots(data.slots);
            },
            error: function(xhr, status, error) {
                console.error("Error fetching slots", status, error);
            }
        });
    }

    function updateSlots(slots) {
        var select = document.getElementById('timeslotSelect');
        select.innerHTML = '';

        slots.forEach(function(slot) {
            var optionText = `${slot.start_time} to ${slot.end_time}`;

            var option = new Option(optionText, `${slot.start_time}-${slot.end_time}`);

            if (!slot.is_available) {
                option.disabled = true;
            }
            select.appendChild(option);
        });
    }


  function amendConfirmation() {
    var selectedDate = document.getElementById("appointmentDate").value;
    var timeslotSelect = document.getElementById("timeslotSelect");
    var selectedTimeSlot = timeslotSelect.options[timeslotSelect.selectedIndex].value;
    var appointmentID = '{{ appointment.appointment_id }}'
    var csrftoken = $('meta[name="csrf-token"]').attr("content");
    var [startTime, endTime] = selectedTimeSlot.split("-");

    $.ajax({
      url: "{% url 'doctor_nurse_appointments:amend_confirmation_handling' %}",
      type: "POST",
      data: {
        id: appointmentID,
        date: selectedDate,
        start_time: startTime,
        end_time: endTime,
        csrfmiddlewaretoken: csrftoken,
      },
      success: function (response) {
        if (response.status === "success") {
          alert(response.message); 
          window.location.href = "{% url 'doctor_nurse_appointments:appointments_list' %}";
        } else {
          alert(response.message);
          window.location.href = "{% url 'doctor_nurse_appointments:appointments_list' %}";
        }
      },
      error: function (xhr, errmsg, err) {
        console.error("AJAX error: " + xhr.status + ": " + errmsg);
        alert("Failed to update the appointment. Please try again.");
        window.location.href = "{% url 'doctor_nurse_appointments:appointments_list' %}";
      },
    });
  }
    </script>
{% endblock %}

DESD/doctor_nurse_appointments/templates/doctor_nurse_cancel.html
{% extends "base_and_header.html" %}
{% load static %}
{% load custom_filters %}
{% block content %}
    <style>
        table,
        label.btn,
        button {
            font-size: large !important;
        }

        .main-wrapper {
            flex-direction: column;
        }

        .btn-table-cell {
            width: 100%;
        }

        td:first-child,
        th:first-child {
            text-align: end;
        }

        th {
            width: 50%;
        }
    </style>
    <main>
        <div class="container">
            <h1>Appointment #{{ id }} cancel details.</h1>
            <div class="table-container">
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Information</th>
                            <th>Details</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Patient Name</td>
                            <td>{{ name }}</td>
                        </tr>
                        <tr>
                            <td>Type</td>
                            <td>{{ type|capfirst }}</td>
                        </tr>
                        <tr>
                            <td>Staff Name</td>
                            <td>{{ staff_name }}</td>
                        </tr>
                        <tr>
                            <td>Date</td>
                            <td>{{ date }}</td>
                        </tr>
                        <tr>
                            <td>Time</td>
                            <td>{{ start_time }} – {{ end_time }}</td>
                        </tr>
                        <tr>
                            <td>Duration</td>
                            <td>{{ duration }} minutes</td>
                        </tr>
                        <tr>
                            <td>Status</td>
                            <td>{{ status|capfirst }}</td>
                        </tr>
                        <tr>
                            <td>Payment Source</td>
                            <td>{{ billing }}</td>
                        </tr>
                        <tr>
                            <td>Cost</td>
                            <td>{{ cost|add_currency_symbol }}</td>
                        </tr>
                        <tr>
                            <td>Reference ID</td>
                            <td>#{{ id }}</td>
                        </tr>
                        <tr>
                            <td>Cancellation Reason</td>
                            <td>{{ cancel_description | title }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <!-- FIX ME: when going back, retain selected filter in appointments list -->
            <button type="button"
                    class="btn btn-lg button btn-main"
                    onclick="navigateToUrl('{% url 'doctor_nurse_appointments:appointments_list' %}')">
                Back
            </button>
        </div>
    </main>
{% endblock %}

DESD/doctor_nurse_appointments/templates/doctor_nurse_forward.html
{% extends "base_and_header.html" %}
{% load static %}
{% load custom_filters %}
{% block content %}
    <style>
        table,
        label.btn,
        button {
            font-size: large !important;
        }

        .main-wrapper {
            flex-direction: column;
        }

        .btn-table-cell {
            width: 100%;
        }

        td:first-child,
        th:first-child {
            text-align: end;
        }

        th {
            width: 50%;
        }
    </style>
    <main>
        <div class="container">
            <h1>Appointment #{{ id }} details.</h1>
            <div class="table-container">
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Information</th>
                            <th>Details</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Patient Name</td>
                            <td>{{ name }}</td>
                        </tr>
                        <tr>
                            <td>Type</td>
                            <td>{{ type|capfirst }}</td>
                        </tr>
                        <tr>
                            <td>Staff Name</td>
                            <td>{{ staff_name }}</td>
                        </tr>
                        <tr>
                            <td>Date</td>
                            <td>{{ date }}</td>
                        </tr>
                        <tr>
                            <td>Time</td>
                            <td>{{ start_time }} – {{ end_time }}</td>
                        </tr>
                        <tr>
                            <td>Duration</td>
                            <td>{{ duration }} minutes</td>
                        </tr>
                        <tr>
                            <td>Status</td>
                            <td>{{ status|capfirst }}</td>
                        </tr>
                        <tr>
                            <td>Outcome</td>
                            <td>{{ outcome|capfirst }}</td>
                        </tr>
                        <tr>
                            <td>Payment Source</td>
                            <td>{{ billing }}</td>
                        </tr>
                        <tr>
                            <td>Cost</td>
                            <td>{{ cost|add_currency_symbol }}</td>
                        </tr>
                        <tr>
                            <td>Reference ID</td>
                            <td>#{{ id }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <!-- FIX ME: when going back, retain selected filter in appointments list -->
            <button type="button"
                    class="btn btn-lg button btn-main"
                    onclick="navigateToUrl('{% url 'doctor_nurse_appointments:appointments_list' %}')">
                Back
            </button>
        </div>
    </main>
{% endblock %}