DESD/DESD/urls.py
"""
URL configuration for DESD project.

The urlpatterns list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    
Add an import:  from my_app import views
Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    
Add an import:  from other_app.views import Home
Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    
Import the include() function: from django.urls import include, path
Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import path, include
from . import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('check_session_data/', views.check_session_data, name='check_session_data'),
    path('', include('login_page.urls'), name='login_page'),
    path('', include('sign_up.urls'), name='signup'),
    path('account_settings/', include('account_settings.urls')),
    path('admin_payments/', include('admin_payments.urls')),
    path('admin_reports/', include('admin_reports.urls')),
    path('admin_staffrates/', include('admin_staffrates.urls')),
    path('admin_appointments/', include('admin_appointments.urls', namespace='appointment_appointments')),
    path('booking/', include("patients_appointments.urls", namespace='booking')),
    path('patient_main/', include("patients_dashboard.urls")),
    path('patient_prescription/', include("patients_prescription.urls"), name='patients_prescription'),
    path('doctor_nurse_main/', include("doctor_nurse_dashboard.urls"), name='doctor_nurse_main'),
    path('doctor_nurse_prescriptions/', include("doctor_nurse_prescriptions.urls"), name='doctor_nurse_prescriptions'),
    path('doctor_nurse_appointments/', include("doctor_nurse_appointments.urls", namespace='doctor_nurse_appointments')),
    path('admin_main/', include("admins_dashboard.urls"), name='admin_main'),
    path('', include('staff_signup.urls'), name='staff_signup'),
    path('', include('patient_signup.urls'), name='patient_signup'),
]

DESD/admin_appointments/urls.py
from django.urls import path
from . import views

app_name = 'admin_appointments'

urlpatterns = [
    path('', views.appointment_details, name="appointment_details"),
    path('update_list/', views.update_list, name='update_list'),
    path('cancel_appointment', views.cancel_appointment, name='cancel_appointment'),
    path('appointment_invoice', views.appointment_invoice, name="appointment_invoice"),
    path('appointment_reason', views.appointment_reason, name='appointment_reason'),
]

DESD/admins_dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.admins_dashboard_view, name='admin_main'),
]

DESD/admins_dashboard/models.py
from django.db import models

# Create your models here.

DESD/admins_dashboard/views.py
from django.shortcuts import render, redirect
from DESD.views import verify_user_role

"""
Renders the main page for admins, passes the user data as context. 
"""
def admins_dashboard_view(request):
    user_data = request.session.get('user_data')
    if not verify_user_role(user_data.get('role'), 'admin'):
        return redirect('/')

    context = {
        'user_data': user_data,
    }

    return render(request, 'admins_dashboard.html', context)

"""
Renders the signup page for admins.
"""
def staffsignup(request):
    response = render(request,'staffSignUpPage.html')
    return response

DESD/admins_dashboard/templates/admins_dashboard.html
{% extends "base_and_header.html" %}
{% load static %}
{% block content %}
    <style>
        .dashboard-main {
            height: 80vh;
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            /* Center content vertically */
        }

        .dashboard-header {
            margin-bottom: 2rem;
            text-align: center;
        }

        .btn-container {
            display: flex;
            flex-wrap: wrap;
            /* Allow buttons to wrap to the next line if needed */
            justify-content: center;
            gap: 1rem;
            /* Add space between buttons */
            max-width: 550px;
            /* Limit width of button container */
            width: 100%;
            /* Ensure container takes full width */
        }

        .btn-max-width {
            width: 100%;
            /* Ensure buttons take full width of container */
        }

        @keyframes pulse {
            0% {
                transform: scale(1);
            }

            50% {
                transform: scale(1.2);
                /* Expand */
            }

            100% {
                transform: scale(1);
            }
        }

        .pulse-animation {
            animation: pulse 1.5s infinite;
            /* Adjust animation duration as needed */
        }

        .pulse-animation.translate-middle {
            transform: translate(-50%, -50%) !important;
        }
    </style>
    <div class="container dashboard-main col-12">
        <div class="dashboard-header">
            <h2>Hi, {{ user_data.name }}.</h2>
        </div>
        <div class="btn-container">
            <button class="btn btn-main btn-lg btn-max-width"
                    type="button"
                    onclick="navigateToUrl('{% url 'patientDetails' %}')">Patients List</button>
            <button class="btn btn-main btn-lg btn-max-width"
                    type="button"
                    onclick="navigateToUrl('{% url 'admin_payment' %}')">Patient Payments</button>
            <button class="btn btn-main btn-lg btn-max-width"
                    type="button"
                    onclick="navigateToUrl('{% url 'staffDetail' %}')">Staff List</button>
            <button class="btn btn-main btn-lg btn-max-width"
                    type="button"
                    onclick="navigateToUrl('{% url 'admin_appointments:appointment_details' %}')">
                Staff Appointments
            </button>
            <button class="btn btn-main btn-lg btn-max-width"
                    type="button"
                    onclick="navigateToUrl('{% url 'admin_staffrate' %}')">Staff Rates</button>
            <button class="btn btn-main btn-lg btn-max-width"
                    type="button"
                    onclick="navigateToUrl('{% url 'admin_report' %}')">Reports</button>
            <button class="btn btn-main btn-lg btn-max-width"
                    type="button"
                    onclick="navigateToUrl('{% url 'index' %}')">Account Settings</button>
            <button class="btn btn-main btn-lg btn-max-width"
                    type="button"
                    onclick="navigateToUrl('{% url 'login_page' %}')">Logout</button>
        </div>
    </div>
    {% comment %} {{ redirect_to_login_immediately }} {% endcomment %}
    {% comment %} <script>
    function FlushSession(prescriptin_assignment_id) {
      request.session.flush();
    } {% endcomment %}
{% endblock %}